import { db, type Category } from './schema';

/**
 * Pre-seed categories from the family Excel ITEMS sheet.
 * Only seeds if categories table is empty.
 */
export async function seedCategories(): Promise<void> {
  const count = await db.categories.count();
  if (count > 0) return;

  const categories: Category[] = [
    {
      id: 'cat-creditos',
      name: 'Créditos casa-40mm-tc',
      icon: '🏠',
      color: '#dc2626',
      order: 1,
      type: 'debt',
      monthlyTarget: 9100000,
    },
    {
      id: 'cat-administraciones',
      name: 'Administraciones',
      icon: '🏢',
      color: '#7c3aed',
      order: 2,
      type: 'fixed',
      monthlyTarget: 1452800,
    },
    {
      id: 'cat-para-gastar',
      name: 'Para gastar',
      icon: '💸',
      color: '#059669',
      order: 3,
      type: 'variable',
      monthlyTarget: 1400000,
    },
    {
      id: 'cat-servicios',
      name: 'Servicios',
      icon: '💡',
      color: '#0891b2',
      order: 4,
      type: 'fixed',
      monthlyTarget: 1070000,
    },
    {
      id: 'cat-cuota-papa',
      name: 'Cuota papá',
      icon: '👨‍👦',
      color: '#ca8a04',
      order: 5,
      type: 'fixed',
      monthlyTarget: 720000,
    },
    {
      id: 'cat-universidad',
      name: 'Universidad',
      icon: '🎓',
      color: '#2563eb',
      order: 6,
      type: 'fixed',
      monthlyTarget: 620000,
    },
    {
      id: 'cat-tanqueadas',
      name: 'Tanqueadas',
      icon: '⛽',
      color: '#ea580c',
      order: 7,
      type: 'variable',
      monthlyTarget: 500000,
    },
    {
      id: 'cat-cdt',
      name: 'CDT',
      icon: '🏦',
      color: '#16a34a',
      order: 8,
      type: 'savings',
      monthlyTarget: 500000,
    },
    {
      id: 'cat-ahorro-alejandro',
      name: 'Ahorro Alejandro',
      icon: '🐷',
      color: '#ec4899',
      order: 9,
      type: 'savings',
      monthlyTarget: 500000,
    },
    {
      id: 'cat-debitos',
      name: 'Débitos',
      icon: '📱',
      color: '#6366f1',
      order: 10,
      type: 'fixed',
      monthlyTarget: 461900,
    },
    {
      id: 'cat-presupuesto-carro',
      name: 'Presupuesto carro',
      icon: '🚗',
      color: '#64748b',
      order: 11,
      type: 'variable',
      monthlyTarget: 300000,
    },
    {
      id: 'cat-dona-rocio',
      name: 'Doña Rocío',
      icon: '🧹',
      color: '#f59e0b',
      order: 12,
      type: 'fixed',
      monthlyTarget: 225000,
    },
    {
      id: 'cat-adicion-cdt',
      name: 'Adición a CDTs',
      icon: '💰',
      color: '#10b981',
      order: 13,
      type: 'savings',
      monthlyTarget: 200000,
    },
    {
      id: 'cat-entrenadora',
      name: 'Entrenadora Valentina',
      icon: '🏋️',
      color: '#f43f5e',
      order: 14,
      type: 'fixed',
      monthlyTarget: 200000,
    },
    {
      id: 'cat-celulares',
      name: 'Celulares',
      icon: '📞',
      color: '#8b5cf6',
      order: 15,
      type: 'fixed',
      monthlyTarget: 165000,
    },
    {
      id: 'cat-peaje-sopetran',
      name: 'Peaje Sopetrán',
      icon: '🛣️',
      color: '#78716c',
      order: 16,
      type: 'variable',
      monthlyTarget: 120000,
    },
    {
      id: 'cat-internet-sopetran',
      name: 'Internet Sopetrán',
      icon: '🌐',
      color: '#0ea5e9',
      order: 17,
      type: 'fixed',
      monthlyTarget: 100000,
    },
    {
      id: 'cat-lavada-carro',
      name: 'Lavada de carro',
      icon: '🚿',
      color: '#06b6d4',
      order: 18,
      type: 'variable',
      monthlyTarget: 70000,
    },
  ];

  await db.categories.bulkAdd(categories);
}
